### ISSUE TITLE
Logo for our app

### ISSUE THREAD

**Issue by CogitoBurrito** [stevieberryman/WintecWaiata#4]
I think we need a logo for our app.

**Comment by stevieberryman** [comment]
Logo to be displayed as the icon for the app

**Comment by stevieberryman** [comment]
Logo to be displayed as the icon for the app. Flutter placeholder at the moment

**Comment by CogitoBurrito** [comment]
Please use flutter_launcher_icons to generate the icon 
[https://pub.dev/packages/flutter_launcher_icons](url)

**Comment by CogitoBurrito** [comment]
Refer to #10
